"""Network probe: connect to each TLS endpoint as several kinds of client.

The probe itself is a POSIX shell script that runs `openssl s_client` (OpenSSL >= 3.5, for
ML-KEM) once per client profile. Building the script here and parsing its output here keeps
the machine that runs it simple: the lab's client container locally, or the scanner
instance in AWS (through SSM), needs nothing but OpenSSL 3.5 and a shell.

Each probe also sends one HTTP request, so it shows up in the lab server's access log
(nginx logs requests, not bare handshakes).
"""
from __future__ import annotations

from dataclasses import asdict, dataclass, field
import ipaddress
import re

from . import algorithms

# ---------------------------------------------------------------------------------------
# Client profiles. The order matters for the report only.
# ---------------------------------------------------------------------------------------


@dataclass(frozen=True)
class Profile:
    id: str
    label: str
    args: tuple
    description: str


PROFILES = [
    Profile("pq-default", "Current browser / OpenSSL 3.5 default", (),
            "Sends X25519MLKEM768 and X25519 key shares, like current Chrome, Firefox and OpenSSL 3.5."),
    Profile("hybrid-late", "Hybrid-capable, classical share first", ("-groups", "X25519:X25519MLKEM768"),
            "Supports X25519MLKEM768 but only sends an X25519 key share. Shows whether the server "
            "insists on hybrid (HelloRetryRequest) or silently accepts classical."),
    Profile("classical", "Classical-only client", ("-groups", "X25519:secp256r1:secp384r1"),
            "No post-quantum support at all, like most clients from before 2024."),
    Profile("hybrid-only", "Hybrid-only client",
            ("-groups", "X25519MLKEM768:SecP256r1MLKEM768:SecP384r1MLKEM1024"),
            "Offers only hybrid groups. Shows whether the server can do hybrid at all."),
    Profile("pq-only", "Pure ML-KEM client", ("-groups", "MLKEM1024:MLKEM768:MLKEM512"),
            "Offers only pure ML-KEM groups (no classical component)."),
    Profile("tls12", "TLS 1.2 client", ("-tls1_2",),
            "Checks whether TLS 1.2 is still accepted. TLS 1.2 has no post-quantum key exchange."),
]
PROFILE_IDS = [p.id for p in PROFILES]

# Lines of s_client output worth keeping. Everything else (hex dumps, the PEM, session
# tickets, master keys) is dropped on the probing machine, which keeps the output small.
KEEP = (
    r"^(>>>|<<<).*(ClientHello|ServerHello|Alert)"
    r"|^ *[0-9]+ s:|^ +(i|a|v):"
    r"|^Peer signature type|^Peer Temp Key|^Server Temp Key|^Negotiated TLS"
    r"|^New, |^Protocol *:|^Verification|^Verify return code|^SSL handshake has"
    r"|error|errno|^CONNECTED|^Connecting|^Terminated|timed out"
)

_HOST_RE = re.compile(r"^[A-Za-z0-9._-]{1,253}$")


def _valid_host(host: str) -> bool:
    try:
        ipaddress.ip_address(host)
        return True
    except ValueError:
        return bool(_HOST_RE.match(host))


@dataclass(frozen=True)
class Target:
    host: str
    port: int
    source: str = "manual"      # where it was discovered: manual, ec2, elbv2, cloudfront, ...
    name: str = ""              # friendly name for the report
    meta: tuple = ()            # extra (key, value) pairs from discovery

    @property
    def endpoint(self) -> str:
        return f"{self.host}:{self.port}"

    def meta_dict(self) -> dict:
        return dict(self.meta)


def parse_target(text: str, source: str = "manual") -> Target:
    """'host:port', 'host' (port 443) or 'host:port name words' -> Target."""
    text = text.strip()
    spec, _, name = text.partition(" ")
    host, sep, port = spec.rpartition(":")
    if not sep:
        host, port = spec, "443"
    if not _valid_host(host) or not port.isdigit() or not 0 < int(port) < 65536:
        raise ValueError(f"not a valid host:port: {text!r}")
    return Target(host, int(port), source, name.strip())


def build_script(targets: list[Target], profiles: list[Profile] | None = None, timeout: int = 10) -> str:
    """The shell script that probes every target with every profile."""
    profiles = profiles or PROFILES
    lines = [
        "#!/bin/sh",
        "# Generated by pqc-inventory. Needs OpenSSL >= 3.5 (ML-KEM) as $OPENSSL or on PATH.",
        'OPENSSL="${OPENSSL:-openssl}"',
        'echo "### OPENSSL $("$OPENSSL" version 2>&1)"',
        f"KEEP='{KEEP}'",
    ]
    n = 0
    for t in targets:
        if not _valid_host(t.host):
            raise ValueError(f"refusing to probe suspicious host name {t.host!r}")
        sni = "" if _is_ip(t.host) else f" -servername {t.host}"
        req = (f"GET / HTTP/1.0\\r\\nHost: {t.host}\\r\\nUser-Agent: pqc-inventory\\r\\n"
               f"Connection: close\\r\\n\\r\\n")
        for p in profiles:
            n += 1
            args = " ".join(p.args)
            lines += [
                f"echo '### PROBE {n} {t.host} {t.port} {p.id}'",
                f"printf '{req}' | timeout {timeout} \"$OPENSSL\" s_client -connect {t.host}:{t.port}"
                f"{sni} {args} -msg 2>&1 | grep -E \"$KEEP\"",
                f"echo '### END {n}'",
            ]
    lines.append("echo '### DONE'")
    return "\n".join(lines) + "\n"


def _is_ip(host: str) -> bool:
    try:
        ipaddress.ip_address(host)
        return True
    except ValueError:
        return False


# ---------------------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------------------


@dataclass
class CertInfo:
    depth: int
    subject: str = ""
    issuer: str = ""
    key: str = ""               # e.g. "EC, (prime256v1)"
    sigalg: str = ""            # e.g. "ecdsa-with-SHA256"
    not_before: str = ""
    not_after: str = ""


@dataclass
class ProbeResult:
    host: str
    port: int
    profile: str
    ok: bool = False
    protocol: str = ""
    cipher: str = ""
    group: str = ""             # negotiated key exchange group ("" if none)
    hrr: bool = False           # server sent a HelloRetryRequest
    peer_sig: str = ""          # CertificateVerify signature scheme
    chain: list = field(default_factory=list)
    bytes_read: int | None = None
    bytes_written: int | None = None
    error: str = ""
    raw: list = field(default_factory=list)

    @property
    def pq(self) -> bool:
        return self.ok and algorithms.is_pq(self.group)

    def to_dict(self) -> dict:
        d = asdict(self)
        d.pop("raw")
        return d


_ALERT_RE = re.compile(r"Alert \[length [0-9a-f]+\], fatal (\S+)")


def parse_output(text: str) -> tuple[str, list[ProbeResult]]:
    """Parse the script output. Returns (openssl version line, results)."""
    version = ""
    results: list[ProbeResult] = []
    cur: ProbeResult | None = None
    for line in text.splitlines():
        if line.startswith("### OPENSSL "):
            version = line[len("### OPENSSL "):].strip()
        elif line.startswith("### PROBE "):
            parts = line.split()
            cur = ProbeResult(host=parts[3], port=int(parts[4]), profile=parts[5])
        elif line.startswith("### END ") and cur is not None:
            _finish(cur)
            results.append(cur)
            cur = None
        elif cur is not None:
            cur.raw.append(line)
    return version, results


def _finish(r: ProbeResult) -> None:
    client_hellos = 0
    cert: CertInfo | None = None
    alert = ""
    for line in r.raw:
        s = line.strip()
        if line.startswith(">>>") and line.rstrip().endswith("ClientHello"):
            client_hellos += 1
        m = _ALERT_RE.search(line)
        if m and line.startswith("<<<"):
            alert = m.group(1)
        if m2 := re.match(r"^New, (\S+), Cipher is (\S+)", s):
            if m2.group(1) != "(NONE)" and m2.group(2) != "(NONE)":
                r.ok = True
                r.protocol, r.cipher = m2.group(1), m2.group(2)
        elif m2 := re.match(r"^Negotiated TLS1\.3 group: (\S+)", s):
            if m2.group(1) != "<NULL>":
                r.group = m2.group(1)
        elif m2 := re.match(r"^(?:Peer|Server) Temp Key: ([^,]+)(?:, ([^,]+))?", s):
            # TLS 1.2: "X25519, 253 bits" or "ECDH, prime256v1, 256 bits"
            first, second = m2.group(1).strip(), (m2.group(2) or "").strip()
            if not r.group:
                r.group = second if first.upper() == "ECDH" and second else first
        elif m2 := re.match(r"^Peer signature type: (\S+)", s):
            r.peer_sig = m2.group(1)
        elif m2 := re.match(r"^SSL handshake has read (\d+) bytes and written (\d+) bytes", s):
            r.bytes_read, r.bytes_written = int(m2.group(1)), int(m2.group(2))
        elif m2 := re.match(r"^(\d+) s:(.*)", s):
            cert = CertInfo(depth=int(m2.group(1)), subject=m2.group(2).strip())
            r.chain.append(cert)
        elif cert is not None and s.startswith("i:"):
            cert.issuer = s[2:].strip()
        elif cert is not None and s.startswith("a:PKEY:"):
            key, _, sig = s[len("a:PKEY:"):].partition("; sigalg:")
            cert.key, cert.sigalg = key.strip(), sig.strip()
        elif cert is not None and s.startswith("v:NotBefore:"):
            nb, _, na = s[len("v:NotBefore:"):].partition("; NotAfter:")
            cert.not_before, cert.not_after = nb.strip(), na.strip()
    r.hrr = client_hellos >= 2
    if not r.ok:
        if alert:
            r.error = alert
        elif any("Name or service not known" in l or "nodename nor servname" in l for l in r.raw):
            r.error = "dns_failure"
        elif any("Connection refused" in l for l in r.raw):
            r.error = "connection_refused"
        elif any("connect:errno" in l for l in r.raw):
            r.error = "connect_failed"
        elif not r.raw or any("Terminated" in l for l in r.raw) or not any("CONNECTED" in l for l in r.raw):
            r.error = "timeout_or_no_response"
        else:
            r.error = "handshake_failed"


def openssl_supports_pq(version_line: str) -> bool:
    m = re.search(r"OpenSSL (\d+)\.(\d+)", version_line)
    return bool(m) and (int(m.group(1)), int(m.group(2))) >= (3, 5)
